import { css } from "goober";
import react from "react";
import react_dom from "react-dom";
import * as ReactJSXDev from "react/jsx-dev-runtime";
import * as ReactJSX from "react/jsx-runtime";
import { dbInstance } from "src/prasi/utils/db-instance";
import { initSite } from "../site/init-site";
import { cx } from "./cx";
import * as import_navigate from "./navigate";
export const initGlobal = (siteReady: typeof window.siteReady) => {
  window.React = react;
  window.ReactDOM = react_dom;
  window.Fragment = react.Fragment;
  window.JSXRuntime = ReactJSX;
  window.JSXDevRuntime = ReactJSXDev;
  window.initSite = initSite;
  window.css = css;
  window.siteReady = siteReady;
  window.cx = cx;
  window.cn = cx;
  window.db = dbInstance();
  window.navigate = import_navigate.navigate;
  window.baseurl = import_navigate.baseurl;
  window.preload = import_navigate.preload;
  window.preloaded = import_navigate.preloaded;
};
