import { dir } from "utils/dir";
import { join, parse } from "path";
import { writeFileSync } from "fs";
export const routeBuild = async () => {
  dir.ensure(`frontend:editor/src/generated`);
  const routes: Record<string, string> = {};
  const files = dir.list(`frontend:editor/src/pages`);
  for (const file of files) {
    const { name, ext } = parse(file);
    if (ext === ".tsx") {
      let route = join(name === "index" ? "." : name).replace(/\\/g, "/");
      route = route === "." ? "/" : route.startsWith("/") ? route : `/${route}`;
      routes[route] = `@/pages${route === "/" ? "" : route}`;
    }
  }
  const content = `\
// AUTOGENERATED FILE. DO NOT EDIT.
export const pageModules: Record<string, () => Promise<any>> = {
${Object.entries(routes)
  .map(([route, path]) => `  "${route}": () => import("${path}"),`)
  .join("\n")}
};`;

  writeFileSync(dir.path(`frontend:src/generated/pages.ts`), content);
};
